class Wfdm extends Phaser.Scene
{
	TILE_SIZE = 16;		// in pixels
	MAP_WIDTH = 40;		// in tiles
	MAP_HEIGHT = 25;	// in tiles

	/* To Do:
		- modify tiles in tile_colors to only include relevant ones e.g. a window tile shouldn't affect the house color description,
		mushrooms shouldn't make a forest "red"
		- add more features, especially for 'ROOF'
		- look into how to do trees
	*/
	// all tile IDs are 1 more than in tiled for some reason
	TILE_COLORS = [
		{
			colorID: 0,
			colorName: "red",
			tileIDs: [
				53, 54, 55, 56,
				65, 66, 67, 68
			]
		},
		{
			colorID: 1,
			colorName: "yellow",
			tileIDs: [
				4, 10, 11, 12, 16, 22, 23, 
				28, 34, 35, 36
			]
		},
		{
			colorID: 2,
			colorName: "brown",
			tileIDs: [
				73, 74, 75, 76,
				85, 86, 87, 88,
				45, 46, 47, 48,
				57, 59, 60, 
				69, 70, 71, 72, 
				81, 82, 83
			]
		},
		{
			colorID: 3,
			colorName: "green",
			tileIDs: [
				4, 5, 6, 7, 8,
				16, 17, 18, 19, 20,
				28, 30, 31, 32
			]
		},
		{
			colorID: 4,
			colorName: "gray",
			tileIDs: [
				49, 50, 51, 52, 
				61, 62, 63, 64,
				77, 78, 79, 80, 
				89, 90, 91, 92
			]
		}
	]

	STRUCTURE_TYPES = [
		{
			name: "house",
			tileIDs: [
				49, 50, 51, 52, 53, 54, 55, 56,
				61, 62, 63, 64, 65, 66, 67, 68,
				73, 74, 75, 76, 77, 78, 79, 80,
				85, 86, 87, 88, 89, 90, 91, 92
			],
			features: {
				"archway": [75, 79],
				"chimney": [52, 56],
				"dormer": [64, 68],
				"door": [86, 87, 88, 90, 91, 92],
				"window": [85, 89],
			},
			substructures : {
				"roof" : [
					49, 50, 51, 52, 60, 61, 62, 63, 64, // gray
					53, 54, 55, 56, 65, 66, 67, 68 // red
				],
			}
		},
		{
			name: "fence",
			tileIDs: [
				45, 46, 47, 48,
				57, 59, 60, 
				69, 70, 71, 72, 
				81, 82, 83
			]
		},
		{
			name: "forest",
			tileIDs: [
				4, 5, 6, 8, 9, 10, 11, 12,
				16, 17, 18, 19, 20, 21, 22, 23, 24,
				28, 29, 30, 31, 32, 33, 34, 35, 36,
				107, 95
			],
			features: {
				"log": [107],
				"beehive": [95],
				"mushroom": [30],
				"sprout": [18],
			},
			/*
			substructures: {
				"tree": [
					3, 15, 27, 9, 10, 11, 21, 22, 23, 33, 34, 35, // yellow
					4, 5, 6, 7, 8, 16, 18, 19, 20, 28, 30, 31, 32 // green
				],
			}
			*/
		}
	];

	DIRECTIONS = [
		{ x: 0, y: -1 }, // up
		{ x: 0, y: 1 },  // down
		{ x: -1, y: 0 }, // left
		{ x: 1, y: 0 }   // right
	];

	MIN_STRUCTURE_SIZE = 3;	// in tiles

	constructor() {
		super("demoScene");
	}

	preload()
	{
		this.load.setPath("./assets/");
		this.load.image("tilemap_tiles", "tilemap_packed.png");                   // packed tilemap
		this.load.tilemapTiledJSON("three-farmhouses", "three-farmhouses.tmj");   // tilemap in JSON
	}

	create()
	{
		this.createMultiLayerMap();		// easier to understand visually for humans; displayed initially
		this.createSingleLayerMap();	// easier to understand visually for computers

		this.getWorldFacts();
		console.log("Map structures (world facts database):");
		console.log(this.structures);
		this.paragraphDescription = this.getDescriptionParagraph();
		console.log(this.paragraphDescription);

		this.setInput();
		this.displayControls();
	}

	// ----- FOR TESTING/VISUALIZATION ----- //
	createMultiLayerMap() { // NEW VERSION: DO THIS AS POST-PROCESSING SINCE THE MAP DATA WILL BE GENERATED BY WFC
		// Create a new tilemap which uses 16x16 tiles, and is 40 tiles wide and 25 tiles tall
		this.multiLayerMap = this.add.tilemap("three-farmhouses", this.TILE_SIZE, this.TILE_SIZE, this.MAP_HEIGHT, this.MAP_WIDTH);

		// Add a tileset to the map
		this.tileset = this.multiLayerMap.addTilesetImage("kenney-tiny-town", "tilemap_tiles");

		// Create the layers
		this.groundLayer = this.multiLayerMap.createLayer("Ground-n-Walkways", this.tileset, 0, 0);
		this.treesLayer = this.multiLayerMap.createLayer("Trees-n-Bushes", this.tileset, 0, 0);
		this.housesLayer = this.multiLayerMap.createLayer("Houses-n-Fences", this.tileset, 0, 0);

		this.groundLayer.setVisible(false);
        this.treesLayer.setVisible(false);
        this.housesLayer.setVisible(false);
	}
	// NEW VERSION: JUST IMPORT MAP DATA GENERATED BY WFC INSTEAD OF USING THIS FUNCTION; NO NEED TO DRAW MAP JUST GET THE ARRAY
	// AND EITHER MERGE THE LAYERS OR ONLY USE THE ARRAY FOR THE STRUCTURES LAYER
	createSingleLayerMap() {
		// Initialize data
		this.singleLayerMapData = [];
		for (let y = 0; y < this.MAP_HEIGHT; y++) {
			this.singleLayerMapData[y] = [];
		}

		// Populate data
		for (let y = 0; y < this.MAP_HEIGHT; y++) {
			for (let x = 0; x < this.MAP_WIDTH; x++) {
				this.singleLayerMapData[y][x] = this.groundLayer.layer.data[y][x].index;

				if (this.treesLayer.layer.data[y][x].index > 0) { // NOT NEEDED LATER AS WFC VERSION WILL ONLY HAVE TWO LAYERS: GROUND AND STRUCT
					this.singleLayerMapData[y][x] = this.treesLayer.layer.data[y][x].index;
				}

				if (this.housesLayer.layer.data[y][x].index > 0) {
					this.singleLayerMapData[y][x] = this.housesLayer.layer.data[y][x].index;
				}
			}
		}

		// console.log(this.singleLayerMapData);

		// Make map NOTE: NOT NEEDED LATER ON
		this.singleLayerMap = this.make.tilemap({
			data: this.singleLayerMapData,
			tileWidth: this.TILE_SIZE,
			tileHeight: this.TILE_SIZE
		});
		this.combinedLayer = this.singleLayerMap.createLayer(0, this.tileset);
		this.combinedLayer.setVisible(true);	// hidden initially
	}

	getWorldFacts() {
		// Initialize
		this.structures = [];

		// Populate
		for (const type of this.STRUCTURE_TYPES) {
			for (const [index, positionArray] of this.getStructures(this.singleLayerMapData, type.tileIDs).entries()) {
				let struct = new Structure(type.name, index, this.getBoundingBox(positionArray));

				struct.qualPosition = this.getStructureQualPosition(positionArray);
				struct.features = this.getStructureFeatures(type, this.singleLayerMapData, positionArray);
				if (type.substructures != null)
				{
					struct.substructures = this.getSubstructures(type, this.singleLayerMapData, positionArray);
				}
				let basePosition = this.colorSeparation(type, positionArray, this.singleLayerMapData);
				struct.colors = this.getColors(this.singleLayerMapData, basePosition);

				this.structures.push(struct);
			}
		}
	}

	getStructures(mapData, structureTiles) {
		// visitedTiles = a copy of mapData where each elem is a bool initialized to false
		const visitedTiles = Array.from({ length: mapData.length }, () => Array(mapData[0].length).fill(false));
		const structures = [];
	
		for (let y = 0; y < mapData.length; y++) {
			for (let x = 0; x < mapData[0].length; x++) {
				
				// Skip if empty or already visited tiles
				if (mapData[y][x] === 0 || visitedTiles[y][x]) continue;
	
				// Flood fill to find connected structure
				const structure = this.floodFill(mapData, x, y, visitedTiles, structureTiles);
	
				// Store structure if it meets criteria
				if (structure.length > this.MIN_STRUCTURE_SIZE) {
					structures.push(structure);
				}
			}
		}
	
		return structures;
	}

	// ISSUE: floodFill assumes that the structure has no gaps, which isn't necessarily the case (forests)
	floodFill(mapData, startX, startY, visitedTiles, structureTiles) {
		const structure = [];
		const stack = [{ x: startX, y: startY }];
	
		while (stack.length > 0) {
			const { x, y } = stack.pop();

			// Skip if:
			if (
				x < 0 || y < 0 || x >= mapData[0].length || y >= mapData.length || 	// out of bounds
				visitedTiles[y][x] ||												// already visited tile
				structureTiles.findIndex((elem) => elem === mapData[y][x]) === -1	// tile is not a structure tile
			) {
				continue;
			}
	
			// Mark as visited and add to structure
			visitedTiles[y][x] = true;
			structure.push({ x, y });
	
			// Add neighbors to stack
			for (const dir of this.DIRECTIONS) {
				stack.push({ x: x + dir.x, y: y + dir.y });
			}
		}
	
		return structure;
	}

	getBoundingBox(structure) {
		let minX = structure[0].x;
		let maxX = structure[0].x;
		let minY = structure[0].y;
		let maxY = structure[0].y;

		for (const { x, y } of structure) {
			if (x < minX) minX = x;
			else if (x > maxX) maxX = x;
			if (y < minY) minY = y;
			else if (y > maxY) maxY = y;
		}

		return {
			topLeft: { minX, minY },
			bottomRight: { maxX, maxY }
		};
	}

	// ----- DESCRIPTION GENERATION -----//
	getDescriptionParagraph()
	{
		let par = "";
		for (let i = 0; i <  this.structures.length; i++)
		{
			let struct = this.structures[i];
			// Initial identification
			par += "There is a";

			for (let j = 0; j < struct.colors.length; j++)
			{
				par = par + " " + struct.colors[j];
				if (j < struct.colors.length - 1)
				{
					par += " and"
				}
			}

			par = par + " " + struct.type + " at the " + struct.qualPosition + " of the map";

			// Substructures
			let hasSubstructures = false;
			for (let j = 0; j < struct.substructures.length; j++)
			{
				hasSubstructures = true;
				if (j == 0)
				{
					par += " with a "
				}

				par = par + struct.substructures[j].colors + " " + struct.substructures[j].type;
				if (j == struct.substructures.length - 2)
				{
					par += ", and "
				}
				else if (j < struct.substructures.length - 1)
				{
					par += ", a "
				}
			}
		
			// Features
			for (let j = 0; j < struct.features.length; j++)
			{
				if (j == 0 && !hasSubstructures)
				{
					par += " with "
				}
				else if (j == 0 && hasSubstructures)
				{
					par += ", "
				}

				par += struct.features[j];
				if (j == struct.features.length - 2)
				{
					par += ", and "
				}
				else if (j < struct.features.length - 1)
				{
					par += ", "
				}
			}
			par += ". "
		}

		return par;
	}

	getStructureQualPosition(positions)
	{
		// describe position on map
		return this.getMapZone(positions[0]);
		// ^ this is using basically a random tile of the structure to determine what zone the structure is in i believe?
		// TODO: i think we should consider calculating the center of the structure's bounding box and use that instead
	}

	getStructureFeatures(type, mapData, positions)
	{
		let features = type.features;
		let structFeaturesList = []

		// describe features
		for(let featureType in features){
			let featureCount = 0;
			for (let {x, y} of positions){ // check for a feature at each position (coord)
				if(features[featureType].includes(mapData[y][x])){
					featureCount++;
				}
			}
			if(featureCount > 0){ 
				if(featureCount > 1){ featureType += "s" } 	// make feature type plural
				structFeaturesList.push(`${featureCount} ${featureType}`);
			}
		}

		return structFeaturesList;
	}

	getSubstructures(type, mapData, positions)
	{
		let substructures = type.substructures;
		let substructList = [];
		let substructPositions = [];

		for(let substructType in substructures){
			for (let {x, y} of positions){ // check for a substructure tile at each position (coord)
				if(substructures[substructType].includes(mapData[y][x])){
					substructPositions.push({x, y});
				}
			}

			const substruct = {
				type: substructType,
				colors: []
			}
			substructList.push(substruct);
		}

		for (let i = 0; i < substructList.length; i++)
		{
			substructList[i].colors = this.getColors(mapData, substructPositions);
		}

		return substructList;
	}

	getColors(mapData, positions)
	{
		let color1 = "";
		let color2 = "";
		let colorsCount = [];

		// init colorsCount
		for (let i = 0; i < this.TILE_COLORS.length; i++)
		{
			colorsCount[i] = 0;
		}

		for (let {x, y} of positions){
			for (const color of this.TILE_COLORS) {
				if (color.tileIDs.includes(mapData[y][x])) {
					colorsCount[color.colorID] += 1;
				}
			}
		}

		let maxColorIndex = 0;
		maxColorIndex = this.getMaxColor(colorsCount); // get the most frequently-occuring color
		for (const color of this.TILE_COLORS) {
			if (maxColorIndex == color.colorID) {
				color1 = color.colorName;
			}
		}
		colorsCount[maxColorIndex] = 0;
		maxColorIndex = this.getMaxColor(colorsCount); // get the next most frequently-occuring color
		if (maxColorIndex == -1)
		{
			return [color1];
		}

		for (const color of this.TILE_COLORS) {
			if (maxColorIndex == color.colorID) {
				color2 = color.colorName;
			}
		}

		return [color1, color2];
	}

	// Helper function for getColors()
	getMaxColor(colorsCount) {
		let maxColorFrequency = 0;
		let maxColorIndex = 0;

		for (let i = 0; i < colorsCount.length; i++) {
			if (colorsCount[i] > maxColorFrequency)
			{
				maxColorFrequency = colorsCount[i];
				maxColorIndex = i;
			}
		}

		if (maxColorFrequency < 1)
			return -1;

		return maxColorIndex;
	}

	// Separate base tiles from substruct tiles to get individual color descriptions
	colorSeparation(type, positions, mapData) {
		if (type.substructures == null)
		{
			return positions;
		}

		let basePosition = [];
		let substructs = type.substructures;

		// describe features
		for (let {x, y} of positions){
			for(let substruct in substructs) {
				if (!substructs[substruct].includes(mapData[y][x])) {
					basePosition.push({x, y});
				}
			}
		}

		return basePosition;
	}

	getMapZone(coords){
		let horizontalSliceSize = this.MAP_HEIGHT / 3;	// top, center, bottom
		let verticalSliceSize = this.MAP_WIDTH / 3;		// right, center, left

		let {x, y} = coords;
		let mapZone = "";

		// find horizonal zone
		if(y < horizontalSliceSize){ 
			mapZone = "top"; 
		} else if(y < 2 * horizontalSliceSize){ 
			mapZone = "center"; 
		} else{ 
			mapZone = "bottom"; 
		}

		// find vertical zone
		if(x < verticalSliceSize){ 
			mapZone += " left"; 
		} else if(x < 2 * verticalSliceSize && mapZone !== "center"){ 
			mapZone += " center"; 
		} else{ 
			mapZone += " right"; 
		}

		return mapZone;
	}
	
	// not currently in use (debug util)
	/*
	printLayer(layer){
		let print = ""
		for(const row of layer){
			for(const i of row){
				print += `${i}`.padStart(2, " ");
				print += ` `
			}
			print += '\n'
		}
		return print;
	}
	*/

	setInput() {
		this.swapMapKey = this.input.keyboard.addKey(Phaser.Input.Keyboard.KeyCodes.M);
		this.swapMapKey.on("down", () => {
			this.groundLayer.setVisible(!this.groundLayer.visible);
			this.treesLayer.setVisible(!this.treesLayer.visible);
			this.housesLayer.setVisible(!this.housesLayer.visible);
			this.combinedLayer.setVisible(!this.combinedLayer.visible);
		});
	}

	displayControls() {
		document.getElementById("description").innerHTML = `
		<h2>Controls</h2>
		Swap maps: M <br>
		Save Screenshot: S
		`;
	}
}